// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef DRIVESUBSYSTEM_H
#define DRIVESUBSYSTEM_H
#include "frc/commands/Subsystem.h"
#include "frc/WPILib.h"
#include "ctre/Phoenix.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class DriveSubSystem: public frc::Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<WPI_TalonSRX> leftFront;
	std::shared_ptr<WPI_TalonSRX> leftRear;
	std::shared_ptr<frc::SpeedControllerGroup> left;
	std::shared_ptr<WPI_TalonSRX> rightFront;
	std::shared_ptr<WPI_TalonSRX> rightRear;
	std::shared_ptr<frc::SpeedControllerGroup> right;
	std::shared_ptr<frc::DifferentialDrive> differentialDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	DriveSubSystem();
	void InitDefaultCommand() override;
	void Periodic() override;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

// Properties
private:
    double leftSpeed;
    double rightSpeed;

// Methods
public:
    void SetLeftSpeed(const double& speed)
    {
        if (speed >= -1.0 && speed <= 1.0)
        {
            this->leftSpeed = speed;
        }
    }

    void SetRightSpeed(const double& speed)
    {
        if (speed >= -1.0 && speed <= 1.0)
        {
            this->rightSpeed = speed;
        }
    }
};

#endif
