// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef LIFT_CMD_H
#define LIFT_CMD_H


#include "frc/commands/Subsystem.h"
#include "Robot.h"

#include "ControllerState.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class LiftCmd: public frc::Command {
public:
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	LiftCmd();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

	void Initialize() override;
	void Execute() override;
	bool IsFinished() override;
	void End() override;
	void Interrupted() override;

// Properties
private:
    LiftSubSystem* liftSubSystem;
    ControllerState* controllerState;

private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES

	// Run Talon's 6 & 7 from left joystick via the drive subsystem
	void OpenLoopExecute();

	// Run Talon's 6 & 7 from left joystick & keep Talon 7 in sync via PID
	void ClosedLoopExecute();
};

#endif
