// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
#include "ctre/Phoenix.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<frc::Encoder> RobotMap::driveTrainWheelEncoder;
std::shared_ptr<WPI_TalonSRX> RobotMap::driveTrainDriverRightFront;
std::shared_ptr<WPI_TalonSRX> RobotMap::driveTrainDriverRightBack;
std::shared_ptr<frc::SpeedControllerGroup> RobotMap::driveTrainDriverRight;
std::shared_ptr<WPI_TalonSRX> RobotMap::driveTrainDriverLeftFront;
std::shared_ptr<WPI_TalonSRX> RobotMap::driveTrainDriverLeftBack;
std::shared_ptr<frc::SpeedControllerGroup> RobotMap::driveTrainDriverLeft;
std::shared_ptr<frc::RobotDrive> RobotMap::driveTrainSpeedControllers;
std::shared_ptr<frc::DoubleSolenoid> RobotMap::aircontrolModuleCubeKicker;
std::shared_ptr<WPI_TalonSRX> RobotMap::cubeIntakeLeftMotor;
std::shared_ptr<WPI_TalonSRX> RobotMap::cubeIntakeRightMotor;
std::shared_ptr<WPI_TalonSRX> RobotMap::cubeIntakeAngler;
std::shared_ptr<WPI_TalonSRX> RobotMap::scissorLiftScissorLiftMotor;
std::shared_ptr<frc::DigitalInput> RobotMap::scissorLiftDigitalInput0;
std::shared_ptr<frc::DigitalInput> RobotMap::scissorLiftDigitalInput1;
std::shared_ptr<frc::Servo> RobotMap::scissorLiftArmLockMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
	//DPP 0.04712
void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    frc::LiveWindow *lw = frc::LiveWindow::GetInstance();

    driveTrainWheelEncoder.reset(new frc::Encoder(2, 3, true, frc::Encoder::k4X));
    lw->AddSensor("DriveTrain", "Wheel Encoder", driveTrainWheelEncoder);
    driveTrainWheelEncoder->SetDistancePerPulse(0.012);
    driveTrainWheelEncoder->SetPIDSourceType(frc::PIDSourceType::kDisplacement);
    driveTrainDriverRightFront.reset(new WPI_TalonSRX(8));
    
    
    driveTrainDriverRightBack.reset(new WPI_TalonSRX(7));
    
    
    driveTrainDriverRight = std::make_shared<frc::SpeedControllerGroup>(*driveTrainDriverRightFront, *driveTrainDriverRightBack  );
    lw->AddActuator("DriveTrain", "DriverRight", driveTrainDriverRight);
    
    driveTrainDriverLeftFront.reset(new WPI_TalonSRX(5));
    
    
    driveTrainDriverLeftBack.reset(new WPI_TalonSRX(6));
    
    
    driveTrainDriverLeft = std::make_shared<frc::SpeedControllerGroup>(*driveTrainDriverLeftBack, *driveTrainDriverLeftFront  );
    lw->AddActuator("DriveTrain", "DriverLeft", driveTrainDriverLeft);
    
    driveTrainSpeedControllers.reset(new frc::RobotDrive(driveTrainDriverRight, driveTrainDriverLeft));
    
    driveTrainSpeedControllers->SetSafetyEnabled(true);
        driveTrainSpeedControllers->SetExpiration(0.1);
        driveTrainSpeedControllers->SetSensitivity(0.5);
        driveTrainSpeedControllers->SetMaxOutput(1.0);

    aircontrolModuleCubeKicker.reset(new frc::DoubleSolenoid(0, 1, 2));
    lw->AddActuator("AircontrolModule", "CubeKicker", aircontrolModuleCubeKicker);
    
    cubeIntakeLeftMotor.reset(new WPI_TalonSRX(3));
    
    
    cubeIntakeRightMotor.reset(new WPI_TalonSRX(10));
    
    
    cubeIntakeAngler.reset(new WPI_TalonSRX(9));
    
    
    scissorLiftScissorLiftMotor.reset(new WPI_TalonSRX(4));
    
    
    scissorLiftDigitalInput0.reset(new frc::DigitalInput(4));
    lw->AddSensor("ScissorLift", "DigitalInput0", scissorLiftDigitalInput0);
    
    scissorLiftDigitalInput1.reset(new frc::DigitalInput(1));
    lw->AddSensor("ScissorLift", "DigitalInput1", scissorLiftDigitalInput1);
    
    scissorLiftArmLockMotor.reset(new frc::Servo(0));
    lw->AddActuator("ScissorLift", "ArmLockMotor", scissorLiftArmLockMotor);
    


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
