// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef POSITION_CONTOLLER_H
#define POSITION_CONTOLLER_H

#include "frc/commands/PIDSubsystem.h"
#include "frc/WPILib.h"
#include "ctre/Phoenix.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class PositionController: public frc::PIDSubsystem {

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<frc::Encoder> encoder;
	std::shared_ptr<WPI_TalonSRX> talonSRX6;
	std::shared_ptr<WPI_TalonSRX> talonSRX5;
	std::shared_ptr<WPI_TalonSRX> talonSRX7;
	std::shared_ptr<WPI_TalonSRX> talonSRX8;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
 public:
	PositionController();
	double ReturnPIDInput() override;
	void UsePIDOutput(double output) override;
	void InitDefaultCommand() override;
	
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS
	std::shared_ptr<frc::PIDSource> GetEncoder();
	std::shared_ptr<frc::PIDOutput> GetTalonSRX6();	// master
	std::shared_ptr<WPI_TalonSRX> GetTalonSRX5();	// slave
	std::shared_ptr<WPI_TalonSRX> GetTalonSRX7();	// slave
	std::shared_ptr<WPI_TalonSRX> GetTalonSRX8();	// slave
};

#endif
