// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Subsystems/HatchSubSystem.h"
#include "Robot.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

HatchSubSystem::HatchSubSystem() : frc::Subsystem("HatchSubSystem")
 {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    compressor1.reset(new frc::Compressor(8));
    ejectorpins.reset(new frc::DoubleSolenoid(8, 1, 0));
    gripper.reset(new frc::DoubleSolenoid(8, 3, 2));
    hatchSwing.reset(new frc::DoubleSolenoid(8, 5, 4));

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    printf("Hatch sub-system initialized\n");
}

void HatchSubSystem::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND 

        //SetDefaultCommand(new Hatch());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void HatchSubSystem::Periodic()
{
}

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


// Put methods for controlling this subsystem
// here. Call these from Commands.

frc::DoubleSolenoid::Value HatchSubSystem::GetPivotState()
{
    return this->hatchSwing->Get();
}

frc::DoubleSolenoid::Value HatchSubSystem::GetGrippperState()
{
    return this->gripper->Get();
}

frc::DoubleSolenoid::Value HatchSubSystem::GetEjectorState()
{
    return this->ejectorpins->Get();
}

void HatchSubSystem::PivotForward()
{
    this->hatchSwing->Set(frc::DoubleSolenoid::kForward);
}

void HatchSubSystem::PivotReverse()
{
    this->hatchSwing->Set(frc::DoubleSolenoid::kReverse);
}

void HatchSubSystem::ExtendGripper()
{
    printf("Gripper extended\n");
    this->gripper->Set(frc::DoubleSolenoid::kForward);
}

void HatchSubSystem::RetractGripper()
{
    printf("Gripper retracted\n");
    this->gripper->Set(frc::DoubleSolenoid::kReverse);
}

void HatchSubSystem::EjectorForward()
{
    this->ejectorpins->Set(frc::DoubleSolenoid::kForward);  
}

void HatchSubSystem::EjectorReverse()
{
    this->ejectorpins->Set(frc::DoubleSolenoid::kReverse);  
}

void HatchSubSystem::EjectorOff()
{
    this->ejectorpins->Set(frc::DoubleSolenoid::kOff);  
}
